# Generated by Django 5.2.5 on 2025-08-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(default='Student', max_length=10)),
                ('L_name', models.CharField(default='Student', max_length=10)),
                ('age', models.IntegerField()),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20)),
                ('gpa', models.IntegerField()),
                ('statust', models.BooleanField()),
                ('report', models.TextField(max_length=300)),
            ],
        ),
    ]
